name: aquawatch
description: AquaWatch - Citizen-science water body health monitoring app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Camera & Photo
  image_picker: ^1.0.7

  # Location
  geolocator: ^10.1.0
  permission_handler: ^11.1.0

  # HTTP
  http: ^1.2.0
  http_parser: ^4.0.2

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
